server:
  port: 8010

spring:
  application:
    name: account-account
  profiles:
    active: test
  cloud:
    nacos:
      discovery:
        server-addr: 192.168.100.120:8848
  datasource:
    driver-class-name: com.mysql.jdbc.Driver
    url: jdbc:mysql://192.168.100.120:3306/bloom?characterEncoding=utf-8&useSSL=false
    username: root
    password: root555
#mybatis的相关配置
mybatis:
  #mapper配置文件
  mapper-locations: classpath:com.little.cloud.dao/*.xml
  type-aliases-package: com.little.cloud.dao
  #开启驼峰命名
  configuration:
    map-underscore-to-camel-case: true