server:
  port: 8090

spring:
  application:
    name: cloud-gateway
  profiles:
    active: dev
  cloud:
    gateway:
      routes:
        - id: product-service
          uri: http://localhost:8012
          predicates:
            - Path=/api/product/**
        - id: account-service
          uri: http://localhost:8010
          predicates:
            - Path=/api/account/**
        - id: order-service
          uri: http://localhost:8011
          predicates:
            - Path=/api/order/**